### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by alexgn100** [markrogoyski/ipv4-subnet-calculator-php#18]
Hello,

would it be possible to integrate arpa from an IP as a function?

**Comment by markrogoyski** [comment]
Hi @MG-100,

Are you asking is it possible to do a reverse IP address mapping to get the domain name associated with an IP address?

For example: "74.6.231.21" => "yahoo.com"

If so, that functionality is already built into PHP. See the built-in function [gethostbyaddr](https://www.php.net/manual/en/function.gethostbyaddr.php).

**Comment by alexgn100** [comment]
> Hi @MG-100,
> 
> Are you asking is it possible to do a reverse IP address mapping to get the domain name associated with an IP address?
> 
> For example: "74.6.231.21" => "yahoo.com"
> 
> If so, that functionality is already built into PHP. See the built-in function [gethostbyaddr](https://www.php.net/manual/en/function.gethostbyaddr.php).

Hello,

I mean for example a arpa for dns:
74.6.231.21 => 21.231.6.74.in-addr.arpa

**Comment by markrogoyski** [comment]
Hi @MG-100,

Thank you for the clarification. I understand that you are asking for the IP address format used to query the DNS PTR record in a reverse DNS lookup. I can add this. Do you have any suggestions on a concise, self-describing name for the function?

Thanks,
Mark

**Comment by alexgn100** [comment]
Hello,

thanks for adding this feature :)

Example Function Name: $sub->getReverseDnsZone();

**Comment by alexgn100** [comment]
Hello,

Have you any eta?

**Comment by markrogoyski** [comment]
Hi @MG-100,

I am working on a new version that will include the ARPA domain. I will try to release it in the next few days. Thank you for your patience.

**Comment by Nevercold** [comment]
Is there any news about the update yet?

**Comment by Nevercold** [comment]
And is there anything for Ipv6?

**Comment by markrogoyski** [comment]
Version [v4.0.0](https://github.com/markrogoyski/ipv4-subnet-calculator-php/releases/tag/v4.0.0) has been released that has this feature (`getIPv4ArpaDomain`) as well as other new features and improvements.

Thank you for your interest in improving the IPv4 SubnetCalculator and your patience while I implemented this new feature in the new version.

**Comment by markrogoyski** [comment]
@Nevercold,
If you have any suggestions or specific feature requests please create a new issue. Thanks.
