### ISSUE TITLE
Extra

### ISSUE THREAD

**Issue by majorwitty** [markrogoyski/ipv4-subnet-calculator-php#2]
Your SubnetCalculator works as is (thanks) but your class creates two properties for network size. You have property declaration for $network. Then, instead of using $network property you create another $network_size property in constructor. The $network_size property is then used throughout your class. $network and $network_size property represents the same value. I changed $network to $network_size in the copy I'm using.

**Comment by markrogoyski** [comment]
Hi.

Thank you for your interest in IPv4 SubnetCalculator. And thank you for pointing out that I had the class property named incorrectly. It's been fixed in the latest version, v2.0.2.
