### ISSUE TITLE
Use case.  

### ISSUE THREAD

**Issue by arebacollins** [markrogoyski/ipv4-subnet-calculator-php#20]
Hello, I am developing an ISP management platform  and am interested in using your library if that's OK with you. My use case : 

1) Define bras
2) Define subnets (each subnet has bras and use case - whether network or clients)
3) generate smaller nested subnets into the main subnet. - For instance, a /22 representing a tower can be broken into two /23, or a couple dozen /30's. 
4) each of the client subnets defined in 3 above also has a vlan attached to it, so whene generating subnets, we define a starting subnet and then as it generates the subnet, it has a vlan attached to this, and a "status" flag which states if the subnet is utilised or available. 

When customer is provisioned service, 
a) subnet flag is changed to assigned 
b) API writes into mikrotik, creating the subnet on the bridge, and assigning the gateway IP to the subnet, and a simple queue is created for the vlan, for the package assigned to the client. 
c) installation instructions are then generated  for the technician, who simply logs to client end devices, and inserts the statis /30 IP and vlan for the client to get service. 

I intend to  use your script for two things: 

a) creating subnets given a master subnet. e.g. create four /24's from one/22 on the fly. 
b) looping through each client subnet and getting the network, gateway, client and broadcast IP's in an array that I can then use to populate my db and write to my routers. 

Please let me knowif it is OK to use it, and how you would recommend implementing efficiently

**Comment by markrogoyski** [comment]
Hi @arebacollins,

Thank you for your interest in the IPv4 SubnetCalculator PHP project. It is free and open source. You are free to use it for any use case you have. If you have any feedback or comments for additional functionality, you can open a feature request issue.

Mark

**Comment by arebacollins** [comment]
<img width="957" alt="Screenshot 2022-01-05 at 12 32 44 am" src="https://user-images.githubusercontent.com/1815222/148127795-d8005463-ee42-4339-9a8d-cff98955fd44.png">

Thanks a heap!
