### ISSUE TITLE
PHP 8.1 compatibility

### ISSUE THREAD

**Issue by sips-richard** [markrogoyski/ipv4-subnet-calculator-php#21]
PHP Deprecated:  Return type of IPv4\SubnetCalculator::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

**Comment by markrogoyski** [comment]
Hi @sips-richard,

What version are you using? Please try [v4.0.0](https://github.com/markrogoyski/ipv4-subnet-calculator-php/releases/tag/v4.0.0) and see if that fixes the issue.

**Comment by sips-richard** [comment]
You are absolutely right! I can only apologise for my blindness here. Thanks for the nudge and for this library! :)
