### ISSUE TITLE
List of ip addresses within subnet

### ISSUE THREAD

**Issue by TheJenne18** [markrogoyski/ipv4-subnet-calculator-php#7]
Would it be possible to develop a method where we can get a array of all the ip addresses that exist in the given subnet?

**Comment by markrogoyski** [comment]
Hi @TheJenne18 
Thanks for your interest in IPv4 SubnetCalculator.

This sounds similar to the feature requested in [issue 4](https://github.com/markrogoyski/ipv4-subnet-calculator-php/issues/4).

Can you confirm if you are requesting the same feature? If so, I'll close this as duplicate and give a higher priority to getting this feature implemented.

Thanks,
Mark

**Comment by TheJenne18** [comment]
@markrogoyski, it is the same feature.

**Comment by markrogoyski** [comment]
Thanks for confirming. Closing issue as it is a duplicate. Will increase the priority for implementing this. Thanks.
